server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${rds_enpoint}:3306/newhorizons?allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: ${rds_password}
    platform: org.hibernate.dialect.MySQL5Dialect
    initialization: always
    validation-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: create